spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor: TRACE